### ISSUE TITLE
Basic auth now fails as Hexonet has implemented 2FA 

### ISSUE THREAD

**Issue by mgeeforce** [WanTanFao/hexonet-dyndns#2]
This has been an awesome dyndns solution for the last few years but as of April 1, 2024, Hexonet has made the 2FA mandatory and the API now requires a one-time password to establish a session.

**Comment by derfabianpeter** [comment]
Hi Mike, thanks for raising this issue. You must be the only user of this library and I respect your braveness to use software that hasn't been maintained for 6 years :D I originally wrote this when I was working at HEXONET but since I left, I didn't really look after this tool.

Unfortunately I won't be of help here. The Python SDK this tool uses has been deprecated in 2017 in favor of a new, more complex SDK. I looked into it a bit, but there's no official documentation on how to implement the OTP login into the tool, and I'm pretty busy these days, not using this tool anymore. 

Sorry to say, but I currently don't have the time to wrangle with HEXONET's often lacking support to fix a tool I don't use anymore. If you're a little into python, this is a good starting point to assess potential fixes: https://centralnicgroup-opensource.github.io/rtldev-middleware-python-sdk/docs/_build/html/quickstart.html#a-minimal-application
